version: '3.8'
services:
  db:
    image: 'mysql:5.7.22'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=admin
    ports:
      - "3307:3306"

  spring_backend:
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db/admin?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: "./"
      dockerfile: Dockerfile
    image: springboot-docker-container
    ports:
      - "8100:8100"







